services:
  redis:
    image: redis:latest
    container_name: myrediss
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "1234", "--databases", "24"]
    restart: unless-stopped